class TEXTS:
    ABOUT_SONG = (
        "**💬 Title:** {0}\n\n"
        "**📺 Channel:** {1} \n"
        "**🕰 Published:** {2} \n"
        "**🔖 Views:** {3} \n"
        "**⏳ Duration:** {4} \n\n"
        "**❆** {5}"
    )
    ABOUT_USER = (
        "**✘ Top User Info:**\n\n"
        "**💬 Name:** {0}\n"
        "**💠 ID:** `{1}`\n"
        "**⚜️ Level:** {2}\n"
        "**🎶 Songs Played:** {3}\n"
        "**〥 Joined Since:** {4}\n\n"
        "**❆** {5}"
    )
    BOOTED = (
        "#START\n\n"
        "**{0} is alive!**\n\n"
        "» Hell-Music Version: `{1}`\n"
        "» Python Version: `{2}`\n"
        "» Pyrogram Version: `{3}`\n"
        "» PyTgCalls Version: `{4}`\n\n"
        "**</>** {5}"
    )
    PING_REPLY = (
        "**📌 Pinged Bot Server!**\n\n"
        "**🏁 Speed:** {0} ms\n"
        "**⏳ Uptime:** {1}\n"
        "**🎶 VC Ping:** {2} ms"
    )
    PLAYING = (
        "**❆** {0}\n\n"
        "**♪ Song Name:** {1}\n"
        "**♪ Duration:** {2}\n"
        "**♪ Auxed By:** {3}"
    )
    PROFILE = (
        "**{0}\nUser Profile**\n\n"
        "**💬 Name:** {1}\n"
        "**💠 ID:** `{2}`\n"
        "**📝 User Type:** {3}\n"
        "**⚜️ Level:** {4}\n"
        "**🎶 Songs Played:** {5}\n"
        "**〥 Joined Since:** {6}\n\n"
        "**❆** {7}"
    )
    QUEUE = (
        "**Added to Queue (#{0})** \n\n"
        "**» Song Name:** {1}\n"
        "**» Duration:** {2}\n"
        "**» Queued By:** {3}"
    )
    SONG_CAPTION = (
        "**⊸ Title:** [{0}]({1})\n\n"
        "**⊸ Views:** {2}\n"
        "**⊸ Duration:** {3}\n"
        "**⊸ Requested By:** {4}\n\n"
        "**❆** {5}"
    )
    SOURCE = (
        "**Source 📦:**\n\n"
        "**Note:** \n» The source code is available on GitHub. You can find the link below.\n"
        "» Every project available under Music Bot are open-source and free to use and modify to your needs.\n"
        "» Anyone pretending to be the developer of this bot and selling the code, is a scammer.\n\n"
        "» Please consider giving a star to the repository if you liked the project.\n"
        "» Feel free to contact us if you need any help regarding the source code.\n\n"
        "❤️🎶 {0}"
    )
    STATS = (
        "**⤞ Server Stats:**\n"
        "    Total Users: `{0} users`\n"
        "    Total Chats: `{1} chats`\n"
        "    Total Gbans: `{2} users`\n"
        "    Blocked Users: `{3} users`\n"
        "    Songs Played: `{4} songs`\n"
        "    Active VC: `{5} vc`\n\n"
        "**⤞ System Stats:**\n"
        "    Core: `{6} cores`\n"
        "    CPU Usage: `{7}`\n"
        "    Disk Usage: `{8}`\n"
        "    RAM Usage: `{9}`\n"
        "    Uptime: `{10}`\n\n"
        "**</>** {11}"
    )
    SYSTEM = (
        "**⤞ System Info:**\n\n"
        "   Core: `{0} cores`\n"
        "   CPU Usage: `{1}`\n"
        "   Disk Usage: `{2}`\n"
        "   RAM Usage: `{3}`\n"
        "   Uptime: `{4}`\n\n"
        "**</>** {5}"
    )
    HELP_ADMIN = (
        "**Authorized Users Commands:**\n\n"
        "**» /auth ; /unauth**\n"
        "    Authorize or unauthorize user to use admins command such as /skip, /pause, etc.\n\n"
        "**» /authlist**\n"
        "    List all authorized users.\n\n"
        "**» /authchat**\n"
        "    This enables all the users in the chat to use admins command such as /skip, /pause, etc.\n\n"
        "**» /mute ; /unmute**\n"
        "    Mute or unmute the ongoing track in the voice chat.\n\n"
        "**» /pause ; /resume**\n"
        "    Pause or resume the ongoing track in the voice chat.\n\n"
        "**» /stop ; /end**\n"
        "    Stop the ongoing track in the voice chat.\n\n"
        "**» /loop**\n"
        "    Loop the playing track in the voice chat. Use [/loop 0] to disable the loop.\n\n"
        "**» /skip**\n"
        "    Skip the playing track in the voice chat.\n\n"
        "**» /replay**\n"
        "    Replay from the beginning of the playing track in the voice chat.\n\n"
        "**» /seek**\n"
        "    Seek the playing track in the voice chat. Use [/seek 10] to seek forward and [/seek-10] to seek backwards.\n\n"
        "**» /clean**\n"
        "    Clear the queue when bot seems to be bugged.\n\n"
    )
    HELP_USER = (
        "**Normal Users Commands:**\n\n"
        "**» /play ; /vplay**\n"
        "    Play replied audio/video file or youtube video or searched query on voice chat.\n\n"
        "**» /fplay ; /fvplay**\n"
        "    Force play replied audio/video file or youtube video or searched query on voice chat.\n\n"
        "**» /favs ; /myfavs ; /favorites**\n"
        "    Show your favorite songs list.\n\n"
        "**» /delfavs**\n"
        "    Delete your favorite songs from your list.\n\n"
        "**» /current ; /playing**\n"
        "    Show the current playing song.\n\n"
        "**» /queue ; /que ; /q**\n"
        "    Show the queued songs list.\n\n"
        "**» /song**\n"
        "    Download the searched song from youtube.\n\n"
        "**» /lyrics**\n"
        "    Get the lyrics of the searched song. Give artist name after ' - ' for accurate results. [/lyrics Without Me - Eminem]\n\n"
        "**» /profile ; /me**\n"
        "    Show your profile and stats.\n\n"
    )
    HELP_SUDO = (
        "**Sudo Users Commands:**\n\n"
        "**» /active**\n"
        "    Check active voice chats of the bot.\n\n"
        "**» /autoend**\n"
        "    Enable or disable autoend inactive voice chats.\n\n"
        "**» /block ; /unblock**\n"
        "    Block or unblock user from using the bot.\n\n"
        "**» /blocklist**\n"
        "    List all blocked users.\n\n"
        "**» /gban ; /ungban**\n"
        "    Globally ban or unban user from using the bot.\n\n"
        "**» /gbanlist**\n"
        "    List all globally banned users.\n\n"
        "**» /logs**\n"
        "    Get the logs of the bot.\n\n"
        "**» /restart**\n"
        "    Restart the bot globally.\n\n"
        "**» /sudolist**\n"
        "    List all sudo users.\n\n"
        "**» /stats**\n"
        "    Show full stats of the bot.\n\n"
    )
    HELP_OTHERS = (
        "**Other Commands:**\n\n"
        "**» /start**\n"
        "    Check if the bot is alive.\n\n"
        "**» /ping**\n"
        "    Check ping of the bot.\n\n"
        "**» /help**\n"
        "    Show this menu.\n\n"
        "**» /sysinfo**\n"
        "    Show system information of the bot.\n\n"
        "**» /leaderboard ; /topusers**\n"
        "    Show the top 10 users with most number of songs played.\n\n"
    )
    HELP_OWNERS = (
        "**Owner Commands:**\n\n"
        "**» /eval ; /run**\n"
        "    Execute the python script.\n\n"
        "**» /exec ; /term ; /sh**\n"
        "    Execute the bash script.\n\n"
        "**» /getvar ; /gvar ; /var**\n"
        "    Get the value of the config variable.\n\n"
        "**» /addsudo**\n"
        "    Add sudo user of the bot who can use sudo commands.\n\n"
        "**» /rmsudo ; /delsudo**\n"
        "    Remove sudo user of the bot.\n\n"
    )
    HELP_GC = (
        "Get the help menu in your PM. "
        "Click the button below!"
    )
    HELP_PM = (
        "**Help ⚙️**\n\n"
        "» All commands are categorized based on their usability and target users.\n"
        "» You can use these buttons below to navigate each category and get respective commands.\n"
        "» Feel free to contact us if you need any help regarding the bot.\n\n"
        "❤️🎶 {0}"
    )
    START_GC = (
        "Yeah, I'm alive! "
        "Wanna listen to some music?"
    )
    START_PM = (
        "**Hello there** {0}**!**\n\n"
        "**I'm** {1} **, a music bot that can play music on Voice Chats.**\n"
        "**Add me to your group and play music freely!**\n\n"
        "» Feel free to dive in, try different commands, and have fun discovering all the possibilities!\n"
        "» Enjoy the music and let us know if you have any suggestions for improvement.\n\n"
        "❤️🎶 @{2}"
    )
    PERFORMER = "[ Team Arc ]"
